#!/usr/bin/perl

$up = $ARGV[0];

$hdr = "";
while ($_ = <STDIN>)
{
    if ($_ =~ /^>(.*)/) 
    { 
	$nexthdr = $1;
	$seq =~ s/\s+//g;
	$l = length($seq);
	$subB = substr($seq,0,20);
	$subE = substr($seq,(length($seq)-20),20);
	if ($hdr) 
	{ 
	    if ($up) 
	    { 
		$seq  =~ tr/[a-z]/[A-Z]/;
		$subB =~ tr/[a-z]/[A-Z]/;
		$subE =~ tr/[a-z]/[A-Z]/;
	    }
	    print "$seq\t$subB\t$subE\t$l\t$hdr\n"; 
	}
	$seq = "";
	$hdr = $nexthdr;
	next; 

    }
    else
    {
	$seq .= $_;
    }

}

$seq =~ s/\s+//g;
$l = length($seq);
$subB = substr($seq,0,20);
$subE = substr($seq,(length($seq)-20),20);
if ($up) 
{ 
    $seq  =~ tr/[a-z]/[A-Z]/;
    $subB =~ tr/[a-z]/[A-Z]/;
    $subE =~ tr/[a-z]/[A-Z]/;
}
print "$seq\t$subB\t$subE\t$l\t$hdr\n"; 


